-- tests/test_balance.lua
package.path = package.path .. ";../src/logic/?.lua"
require("balance")

describe("Balance.applyABHit", function()
    it("adds 5 to position", function()
        assert.equals(5,  Balance.applyABHit(0))
        assert.equals(15, Balance.applyABHit(10))
    end)
end)

describe("Balance.applyArrowHit", function()
    it("adds accuracy to position", function()
        assert.equals(3, Balance.applyArrowHit(0, 3))
        assert.equals(8, Balance.applyArrowHit(5, 3))
    end)
end)

describe("Balance.applyWrongPress", function()
    it("subtracts 5 from position", function()
        assert.equals( 5, Balance.applyWrongPress(10))
        assert.equals(-5, Balance.applyWrongPress(0))
    end)
end)

describe("Balance.applyMissPenalty", function()
    it("no penalty within grace period", function()
        assert.equals(10, Balance.applyMissPenalty(10, 3))
        assert.equals(10, Balance.applyMissPenalty(10, 5))
    end)
    it("applies -0.3 after grace period", function()
        local result = Balance.applyMissPenalty(10, 6)
        assert.is_true(math.abs(result - 9.7) < 0.001)
    end)
end)

describe("Balance.clamp", function()
    it("clamps to +maxOffset", function()
        assert.equals(50, Balance.clamp(999, 50))
    end)
    it("clamps to -maxOffset", function()
        assert.equals(-50, Balance.clamp(-999, 50))
    end)
    it("leaves in-range values unchanged", function()
        assert.equals(25, Balance.clamp(25, 50))
    end)
end)

describe("Balance win/lose", function()
    it("isWin true at exactly +maxOffset", function()
        assert.is_true(Balance.isWin(50, 50))
        assert.is_false(Balance.isWin(49, 50))
    end)
    it("isLose true at exactly -maxOffset", function()
        assert.is_true(Balance.isLose(-50, 50))
        assert.is_false(Balance.isLose(-49, 50))
    end)
end)
